# 构建阶段
FROM maven:3.8.1-jdk-11 AS build
WORKDIR /app
COPY . .
RUN mvn clean package

# 运行阶段
FROM openjdk:11-jre-slim
COPY --from=build /website/target/mywebsite.jar /website/mywebsite.jar
CMD ["java", "-jar", "/website/mywebsite.jar"]
